language: php

dist: trusty

env:
  global:
  - COMPOSER_ROOT_VERSION="1.0.x-dev"

matrix:
  include:
  - php: 5.6
    env: DB=MYSQL PHPCS_TEST=1 PHPUNIT_TEST=1
  - php: 7.0
    env: DB=PGSQL PHPUNIT_TEST=1
  - php: 7.1
    env: DB=MYSQL PHPUNIT_COVERAGE_TEST=1
