SilverStripe\Assets\File:
  extensions:
  - SilverStripeSVGGO\Extensions\SVGExtension
  allowed_extensions:
  - svg
  app_categories:
    image:
    - svg
  class_for_file_extension:
    svg:  SilverStripe\Assets\Image    
SilverStripe\Assets\Image:
  extensions:
  - SilverStripeSVGGO\Extensions\SVGExtension
  allowed_extensions:
  - svg
  app_categories:
    image:
    - svg
